language: node_js
node_js:
  - "6"
before_install:
  - travis_wait npm install
script:
  - npm run coverage
after_success:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
